#!/usr/bin/env python3
r"""leanos_paper.py -- every number in leanos.tex, written by the run that measured it.

Same rule as crustos_eq.py: a count, a time or a verdict that appears in the
document is a macro in gen/leanos_facts.tex, and nothing there is typed by
hand.  The document quotes the shipped Python by \lstinputlisting from the
crust tree, so what the paper shows is what the compiler read.

    python3 leanos_paper.py             # gen/leanos_facts.tex, gen/*.lean
    python3 leanos_paper.py --no-lean   # skip the second kernel
"""
import os
import shutil
import subprocess
import sys
import threading
import time

import hoare as H

HERE = os.path.dirname(os.path.abspath(__file__))
GEN = os.path.join(HERE, 'gen')
CRUST = os.environ.get('CRUST_DIR') or os.path.join(HERE, '..', 'crust')
LEAN = shutil.which('lean') or next(
    (p for p in (os.path.expanduser('~/.local/lean/bin/lean'),
                 os.path.expanduser('~/.elan/bin/lean'))
     if os.path.exists(p)), None)


def macro(name, value):
    return '\\newcommand{\\%s}{%s}\n' % (name, value)


def lean_check(path):
    """(seconds, ok, names that carry no axioms), or None without lean."""
    if not LEAN:
        return None
    t0 = time.time()
    run = subprocess.run([LEAN, path], capture_output=True, text=True,
                         timeout=900)
    clean = [line.split("'")[1].split('.')[-1] for line in run.stdout.splitlines()
             if 'does not depend on any axioms' in line]
    return time.time() - t0, run.returncode == 0, clean


def lift_tally():
    """How much of crustos/kernel.c the IL lift reaches, and why not the rest."""
    sys.path.insert(0, CRUST)
    from tests.test_ilproof import il_of
    from shivyc.ilproof import lift, LiftError
    import collections
    kernel = os.path.join(CRUST, 'crustos', 'kernel.c')
    with open(kernel) as fh:
        src = fh.read()
    cwd = os.getcwd()
    os.chdir(os.path.dirname(kernel))
    try:
        il, table = il_of(src, path=kernel)
    finally:
        os.chdir(cwd)
    ok, why = [], collections.Counter()
    for fn in il.commands:
        try:
            lift(il, table, fn)
            ok.append(fn)
        except LiftError as exc:
            why[str(exc).split(':')[0].strip()] += 1
    memory = sum(v for k, v in why.items()
                 if k.split()[0] in ('ReadAt', 'AddrOf', 'SetAt'))
    return len(il.commands), len(ok), sum(why.values()), memory


def main(run_lean=True):
    sys.setrecursionlimit(300000)
    os.makedirs(GEN, exist_ok=True)
    out = ['% generated by leanos_paper.py -- do not edit\n']

    total, lifted, refused, memory = lift_tally()
    out += [macro('liftTotal', total), macro('liftReached', lifted),
            macro('liftRefused', refused), macro('liftMemory', memory)]

    import elfcheck_eq
    import memmap_eq
    import threads_eq
    import alloc_eq
    import loader_eq
    for mod, tag in ((elfcheck_eq, 'elf'), (memmap_eq, 'mem'),
                     (threads_eq, 'thr'), (alloc_eq, 'alc'), (loader_eq, 'ldr')):
        t0 = time.time()
        env, facts, model = mod.build()
        out.append(macro(tag + 'BuildSeconds', '%.1f' % (time.time() - t0)))
        names = getattr(mod, 'THEOREMS', list(facts))
        out.append(macro(tag + 'Theorems', len(names)))
        out.append(macro(tag + 'Functions', len(model)))
        src = mod.lean_source(env)
        path = os.path.join(GEN, tag + '.lean')
        with open(path, 'w') as fh:
            fh.write(src)
        out.append(macro(tag + 'LeanLines', src.count('\n')))
        if run_lean:
            checked = lean_check(path)
            if checked:
                secs, ok, clean = checked
                out.append(macro(tag + 'LeanSeconds', '%.1f' % secs))
                out.append(macro(tag + 'LeanVerdict',
                                 'accepted' if ok else 'REJECTED'))
                out.append(macro(tag + 'LeanNoAxioms', len(clean)))
    # the switcher is lifted from the compiled IL rather than modelled
    sys.path.insert(0, os.path.join(CRUST, 'tests'))
    from tests import test_switch_lift as sw
    st = sw._build()
    out.append(macro('swFunctions', len(sw.FUNCTIONS)))
    out.append(macro('swTheorems', len(st['facts'])))
    out.append(macro('swRegs', len(sw.REGS)))
    if run_lean and LEAN:
        import leanexport as X
        names = sorted(st['facts'])
        slow = st['hoare'].prelude(fast=False)
        values = {n: st['lean4'].value_of(slow, n) for n in st['hoare'].ACCELERATED}
        src, _ = X.export(st['env'], names, values, ['#print axioms ' + n for n in names])
        path = os.path.join(GEN, 'sw.lean')
        with open(path, 'w') as fh:
            fh.write(src)
        secs, ok, clean = lean_check(path)
        out.append(macro('swLeanSeconds', '%.1f' % secs))
        out.append(macro('swLeanVerdict', 'accepted' if ok else 'REJECTED'))
        out.append(macro('swLeanNoAxioms', len(clean)))
    # the whole environment, as crustos_eq counts it
    import lean4 as L4
    out.append(macro('preludeDecls', len(H.prelude())))

    if LEAN:
        ver = subprocess.run([LEAN, '--version'], capture_output=True,
                             text=True).stdout.strip()
        out.append(macro('leanVersion', ver.split('(version ')[1].split(',')[0]))
    else:
        out.append(macro('leanVersion', 'not installed'))
    out.append(macro('crustDir', CRUST.replace('_', r'\_')))

    with open(os.path.join(GEN, 'leanos_facts.tex'), 'w') as fh:
        fh.writelines(out)
    print(''.join(out))


if __name__ == '__main__':
    threading.stack_size(512 * 1024 * 1024)
    t = threading.Thread(target=lambda: main('--no-lean' not in sys.argv))
    t.start()
    t.join()
