#!/usr/bin/env python3
r"""rustproof_paper.py -- every number in rustproof.tex, written by the run that
measured it.

Same rule as leanos_paper.py: a count, a time or a verdict that appears in the
document is a macro in gen/rustproof_facts.tex, and nothing there is typed by
hand.  The document quotes the shipped Rust and Python by \lstinputlisting
from the crust tree, and the lifted models it shows are written by this run
into gen/, so what the paper shows is what the prover read.

    python3 rustproof_paper.py             # gen/rustproof_facts.tex, gen/*.lean
    python3 rustproof_paper.py --no-lean   # skip the second kernel
"""
import os
import shutil
import subprocess
import sys
import threading
import time

HERE = os.path.dirname(os.path.abspath(__file__))
GEN = os.path.join(HERE, 'gen')
CRUST = os.environ.get('CRUST_DIR') or os.path.join(HERE, '..', 'crust')
LEAN = shutil.which('lean') or next(
    (p for p in (os.path.expanduser('~/.local/lean/bin/lean'),
                 os.path.expanduser('~/.elan/bin/lean'))
     if os.path.exists(p)), None)


# `bump` as the first Rust port wrote it, before the prover's open
# obligation was read as the bug it was.  Line numbers are this text's.
FIRST_PORT_BUMP = """\
#[ensures(used <= result)]
pub fn bump(bases: &[u64], sizes: &[u64], owners: &[u32], tid: u32,
            heap: usize, used: u64, n: u64) -> u64 {
    if heap < bases.len() && heap < owners.len() && heap < sizes.len() {
        if owners[heap] >= 1 && owners[heap] - 1 == tid {
            if used + n <= sizes[heap] {
                return used + n;
            }
        }
    }
    used
}
"""

BOUNDS_LEMMAS = ('add_le_add_right', 'add_le_add', 'add_le_of_le_sub',
                 'lt_le', 'not_lt_le', 'not_le_lt', 'nth_all_le')


def macro(name, value):
    return '\\newcommand{\\%s}{%s}\n' % (name, value)


def tex(s):
    return str(s).replace('_', r'\_').replace('#', r'\#').replace('%', r'\%')


def lean_check(path):
    if not LEAN:
        return None
    t0 = time.time()
    run = subprocess.run([LEAN, path], capture_output=True, text=True,
                         timeout=900)
    clean = [line for line in run.stdout.splitlines()
             if 'does not depend on any axioms' in line]
    return time.time() - t0, run.returncode == 0, len(clean)


def source(path):
    with open(path) as fh:
        return fh.read()


def count_tests(path, cls=None):
    """`def test_` methods in a test file, optionally within one class."""
    text = source(path)
    if cls:
        start = text.index('class %s' % cls)
        end = text.find('\nclass ', start + 1)
        text = text[start:end if end > 0 else None]
    return text.count('    def test_')


def main(run_lean=True):
    sys.setrecursionlimit(300000)
    os.makedirs(GEN, exist_ok=True)
    sys.path.insert(0, CRUST)
    sys.path.insert(0, os.path.join(CRUST, 'tools'))
    sys.path.insert(0, HERE)
    import hoare as H
    import lean4 as L
    import leanexport as X
    import crustproof as C
    from shivyc.rustproof import lift_all, lift
    import rustprove
    out = ['% generated by rustproof_paper.py -- do not edit\n']

    # -- sizes of what the reader is asked to read ---------------------------
    for tag, rel in (('kernelLines', 'lean4.py'), ('hoareLines', 'hoare.py'),
                     ('exportLines', 'leanexport.py')):
        out.append(macro(tag, source(os.path.join(HERE, rel)).count('\n')))
    for tag, rel in (('liftLines', 'shivyc/rustproof.py'),
                     ('proveLines', 'tools/rustprove.py'),
                     ('crustLines', 'shivyc/crust.py')):
        out.append(macro(tag, source(os.path.join(CRUST, rel)).count('\n')))
    extras = os.path.join(CRUST, 'tests', 'test_crust_extras.py')
    out.append(macro('contractTests', count_tests(extras, 'TestContracts')))
    out.append(macro('extrasTests', count_tests(extras)))
    out.append(macro('rustproofTests',
                     count_tests(os.path.join(CRUST, 'tests',
                                              'test_rustproof.py'))))

    # -- regs.rs: the first Rust theorem ---------------------------------------
    regs = source(os.path.join(CRUST, 'leanos', 'regs.rs'))
    prover = rustprove.Prover(regs)
    lifted = prover.lifted['elf_regs_for_class']
    with open(os.path.join(GEN, 'elf_regs_lifted.py'), 'w') as fh:
        fh.write(lifted.source)
    out.append(macro('regsEnsures', tex(' and '.join(lifted.ensures))))
    t0 = time.time()
    proved = prover.contract('elf_regs_for_class')
    out.append(macro('regsProved', 'proved' if proved else 'NOT PROVED'))
    out.append(macro('regsSeconds', '%.2f' % (time.time() - t0)))
    out.append(macro('regsFalseBound',
                     'refused' if not prover.contract('elf_regs_for_class',
                                                      ['result <= 15'])
                     else 'ACCEPTED'))
    out.append(macro('classForRegsProved',
                     'proved' if prover.contract('class_for_regs')
                     else 'NOT PROVED'))
    out.append(macro('classCoversProved',
                     'proved' if prover.contract('class_covers') else 'open'))
    # -- the safety lift over a table of shapes ----------------------------------
    from tests.test_rustproof import SAFETY, SAFE
    sp = rustprove.Prover(SAFETY)
    rows, agree = [], True
    for name, expected in SAFE.items():
        verdicts = sp.safety(name)
        ok = all(v for _, v in verdicts)
        agree = agree and ok == expected
        rows.append('\\texttt{%s} & %d & %s \\\\' % (
            tex(name), len(verdicts), 'all proved' if ok else 'open'))
    with open(os.path.join(GEN, 'safety_table.tex'), 'w') as fh:
        fh.write('\n'.join(rows) + '\n\\bottomrule\n')
    out.append(macro('safetyShapes', len(SAFE)))
    out.append(macro('safetyAgrees', 'agree' if agree else 'DISAGREE'))
    with open(os.path.join(GEN, 'early_sub_safe.py'), 'w') as fh:
        fh.write(lift(SAFETY, 'early_sub').safety())

    # -- alloc.rs -----------------------------------------------------------------
    alloc = source(os.path.join(CRUST, 'leanos', 'alloc.rs'))
    ap = rustprove.Prover(alloc)
    out.append(macro('allocRefused', len(ap.refused)))
    out.append(macro('allocFunctions', len(ap.lifted)))
    with open(os.path.join(GEN, 'bump_lifted.py'), 'w') as fh:
        fh.write(ap.lifted['bump'].source)
    t0 = time.time()
    total = proved_n = 0
    rows, opens = [], []
    for name in sorted(ap.lifted):
        fn = ap.lifted[name]
        if fn.ensures:
            v = ap.contract(name)
            rows.append('\\texttt{%s} & ensures \\texttt{%s} & %s \\\\' % (
                tex(name), tex(' and '.join(fn.ensures)),
                'proved' if v else 'open'))
        for label, ok in ap.safety(name):
            total += 1
            proved_n += ok
            rows.append('\\texttt{%s} & %s & %s \\\\' % (
                tex(name), tex(label), 'proved' if ok else 'open'))
            if not ok:
                opens.append(label)
    out.append(macro('allocSeconds', '%.1f' % (time.time() - t0)))
    with open(os.path.join(GEN, 'alloc_table.tex'), 'w') as fh:
        fh.write('\n'.join(rows) + '\n\\bottomrule\n')
    out.append(macro('allocObligations', total))
    out.append(macro('allocProved', proved_n))
    out.append(macro('allocOpen', total - proved_n))
    out.append(macro('bumpMonotone',
                     'proved' if ap.contract('bump') else 'open'))
    from tests.test_alloc_model import CORPUS
    out.append(macro('allocCorpusRows', len(CORPUS)))

    # -- the first port's bump, kept to show what the prover said of it --------
    # Its guard evaluated `used + n` in order to test whether it fitted.  The
    # verdicts below are measured on it every run: the overflow at the guard
    # is refused, and the one behind the guard is proved.
    old = rustprove.Prover(FIRST_PORT_BUMP)
    verdicts = dict(old.safety('bump'))
    guard = next(k for k in verdicts if 'overflow' in k and 'line 6)' in k)
    ret = next(k for k in verdicts if 'overflow' in k and 'line 7)' in k)
    out.append(macro('oldGuardAdd', 'refused' if not verdicts[guard]
                     else 'PROVED'))
    out.append(macro('oldReturnAdd', 'proved' if verdicts[ret] else 'open'))
    half = 2 ** 63
    sys.path.insert(0, os.path.join(CRUST, 'tests'))
    from tests.test_rustproof import _compile_and_print
    got = _compile_and_print(alloc, [
        'bump(&[0u64][..], &[100u64][..], &[1u32][..], 0, 0, %du64, %du64)'
        % (half, half)])
    out.append(macro('overflowAnswer', r'2^{63}' if got == [half]
                     else str(got)))
    out.append(macro('boundsLemmas', len(BOUNDS_LEMMAS)))
    out.append(macro('boundsLemmasAll', 'all' if all(
        n in H.prelude() for n in BOUNDS_LEMMAS) else 'NOT ALL'))

    # -- the second kernel: every certificate, not one ----------------------------
    # Each obligation lean4.py settled above left a certificate; every one of
    # them is written as a Lean file and put to Lean 4.
    certs = prover.certificates + sp.certificates + ap.certificates
    out.append(macro('rustCertificates', len(certs)))
    if run_lean and LEAN:
        import rustlean
        t0 = time.time()
        verdicts = rustprove.in_big_stack(
            lambda: rustlean.check(certs, os.path.join(GEN, 'lean_rust'),
                                   lean=LEAN))
        agreed = [v for v in verdicts if v.agreed]
        out.append(macro('rustLeanAgreed', len(agreed)))
        out.append(macro('rustLeanSeconds', '%.1f' % (time.time() - t0)))
        out.append(macro('rustLeanVerdict',
                         'all' if len(agreed) == len(certs) else 'NOT ALL'))
        regs_v = next(v for v in verdicts
                      if v.name == 'rust_elf_regs_for_class_ensures')
        out.append(macro('regsLeanSeconds', '%.1f' % regs_v.seconds))
        out.append(macro('regsLeanVerdict',
                         'accepted' if regs_v.accepted else 'REJECTED'))
        out.append(macro('regsLeanNoAxioms', int(regs_v.axiom_free)))
        shutil.copy(regs_v.path, os.path.join(GEN, 'rust_elf_regs.lean'))

    # -- compact numerals ---------------------------------------------------------
    def timed(length, bounds):
        t0 = time.time()
        try:
            r = C.check(length, bounds)
        except Exception as exc:
            r = str(exc)
        return time.time() - t0, r
    for tag, n, b in (('numSixtyFour', 64, {'len>=': 64}),
                      ('numMillion', 10 ** 6, {'len>=': 64}),
                      ('numUThirtyTwo', 2 ** 32 - 1, {'len>=': 64}),
                      ('numUSixtyFour', 2 ** 64 - 1, {'len<=': 2 ** 64 - 1})):
        secs, r = timed(n, b)
        out.append(macro(tag + 'Seconds', '%.4f' % secs))
        out.append(macro(tag + 'Verdict',
                         'proved' if str(r).startswith('proved') else 'other'))
    out.append(macro('numDivByFour',
                     'not proved' if 'not proved' in
                     str(timed(2 ** 32 - 1, {'div-by': 4})[1]) else 'PROVED'))
    out.append(macro('litIsOneNode',
                     'yes' if isinstance(L.numeral(2 ** 64 - 1), L.NatLit)
                     else 'NO'))
    out.append(macro('litDefEq', 'equal' if L.definitionally_equal(
        L.unary(5), L.numeral(5), L.GLOBAL_ENV) else 'NOT EQUAL'))
    out.append(macro('preludeDecls', len(H.prelude())))
    out.append(macro('acceleratedOps', len(H.ACCELERATED)))

    # -- kernel and prover selftests, as the run sees them --------------------------
    for tag, cmd in (('kernelChecks', ['python3', 'lean4.py', '--selftest']),
                     ('hoareChecks', ['python3', 'hoare.py'])):
        run = subprocess.run(cmd, cwd=HERE, capture_output=True, text=True,
                             timeout=900)
        last = run.stdout.strip().splitlines()[-1]
        out.append(macro(tag, last.split()[0]))
        out.append(macro(tag + 'Verdict',
                         'all passed' if 'all passed' in last else 'FAILED'))

    if LEAN:
        ver = subprocess.run([LEAN, '--version'], capture_output=True,
                             text=True).stdout.strip()
        out.append(macro('leanVersion', ver.split('(version ')[1].split(',')[0]))
    else:
        out.append(macro('leanVersion', 'not installed'))
    out.append(macro('rustleanLines',
                     source(os.path.join(HERE, 'rustlean.py')).count('\n')))
    out.append(macro('crustDir', CRUST.replace('_', r'\_')))

    with open(os.path.join(GEN, 'rustproof_facts.tex'), 'w') as fh:
        fh.writelines(out)
    print(''.join(out))


if __name__ == '__main__':
    threading.stack_size(512 * 1024 * 1024)
    t = threading.Thread(target=lambda: main('--no-lean' not in sys.argv))
    t.start()
    t.join()
