#!/usr/bin/env python3
r"""rustproof_paper.py -- every number in rustproof.tex, written by the run that
measured it.

Same rule as leanos_paper.py: a count, a time or a verdict that appears in the
document is a macro in gen/rustproof_facts.tex, and nothing there is typed by
hand.  The document quotes the shipped Rust and Python by \lstinputlisting
from the crust tree, and the lifted models it shows are written by this run
into gen/, so what the paper shows is what the prover read.

    python3 rustproof_paper.py             # gen/rustproof_facts.tex, gen/*.lean
    python3 rustproof_paper.py --no-lean   # skip the second kernel
"""
import os
import shutil
import subprocess
import sys
import threading
import time

HERE = os.path.dirname(os.path.abspath(__file__))
GEN = os.path.join(HERE, 'gen')
CRUST = os.environ.get('CRUST_DIR') or os.path.join(HERE, '..', 'crust')
LEAN = shutil.which('lean') or next(
    (p for p in (os.path.expanduser('~/.local/lean/bin/lean'),
                 os.path.expanduser('~/.elan/bin/lean'))
     if os.path.exists(p)), None)


def macro(name, value):
    return '\\newcommand{\\%s}{%s}\n' % (name, value)


def tex(s):
    return str(s).replace('_', r'\_').replace('#', r'\#').replace('%', r'\%')


def lean_check(path):
    if not LEAN:
        return None
    t0 = time.time()
    run = subprocess.run([LEAN, path], capture_output=True, text=True,
                         timeout=900)
    clean = [line for line in run.stdout.splitlines()
             if 'does not depend on any axioms' in line]
    return time.time() - t0, run.returncode == 0, len(clean)


def source(path):
    with open(path) as fh:
        return fh.read()


def count_tests(path, cls=None):
    """`def test_` methods in a test file, optionally within one class."""
    text = source(path)
    if cls:
        start = text.index('class %s' % cls)
        end = text.find('\nclass ', start + 1)
        text = text[start:end if end > 0 else None]
    return text.count('    def test_')


def main(run_lean=True):
    sys.setrecursionlimit(300000)
    os.makedirs(GEN, exist_ok=True)
    sys.path.insert(0, CRUST)
    sys.path.insert(0, os.path.join(CRUST, 'tools'))
    sys.path.insert(0, HERE)
    import hoare as H
    import lean4 as L
    import leanexport as X
    import crustproof as C
    from shivyc.rustproof import lift_all, lift
    import rustprove
    out = ['% generated by rustproof_paper.py -- do not edit\n']

    # -- sizes of what the reader is asked to read ---------------------------
    for tag, rel in (('kernelLines', 'lean4.py'), ('hoareLines', 'hoare.py'),
                     ('exportLines', 'leanexport.py')):
        out.append(macro(tag, source(os.path.join(HERE, rel)).count('\n')))
    for tag, rel in (('liftLines', 'shivyc/rustproof.py'),
                     ('proveLines', 'tools/rustprove.py'),
                     ('crustLines', 'shivyc/crust.py')):
        out.append(macro(tag, source(os.path.join(CRUST, rel)).count('\n')))
    extras = os.path.join(CRUST, 'tests', 'test_crust_extras.py')
    out.append(macro('contractTests', count_tests(extras, 'TestContracts')))
    out.append(macro('extrasTests', count_tests(extras)))
    out.append(macro('rustproofTests',
                     count_tests(os.path.join(CRUST, 'tests',
                                              'test_rustproof.py'))))

    # -- regs.rs: the first Rust theorem ---------------------------------------
    regs = source(os.path.join(CRUST, 'leanos', 'regs.rs'))
    prover = rustprove.Prover(regs)
    lifted = prover.lifted['elf_regs_for_class']
    with open(os.path.join(GEN, 'elf_regs_lifted.py'), 'w') as fh:
        fh.write(lifted.source)
    out.append(macro('regsEnsures', tex(' and '.join(lifted.ensures))))
    t0 = time.time()
    proved = prover.contract('elf_regs_for_class')
    out.append(macro('regsProved', 'proved' if proved else 'NOT PROVED'))
    out.append(macro('regsSeconds', '%.2f' % (time.time() - t0)))
    out.append(macro('regsFalseBound',
                     'refused' if not prover.contract('elf_regs_for_class',
                                                      ['result <= 15'])
                     else 'ACCEPTED'))
    out.append(macro('classForRegsProved',
                     'proved' if prover.contract('class_for_regs')
                     else 'NOT PROVED'))
    out.append(macro('classCoversProved',
                     'proved' if prover.contract('class_covers') else 'open'))
    if run_lean and LEAN:
        def work():
            env, sig = prover.fresh_env(lifted)
            proc = H.read_procedure(lifted.source, env, sig, lifted.ensures)
            proof = H.by_every_bool(env, proc.obligation,
                                    unfolding={'elf_regs_for_class'})
            L.define(env, 'rust_elf_regs_bounded', proc.obligation, proof)
            slow = H.prelude(fast=False)
            values = {n: L.value_of(slow, n) for n in H.ACCELERATED}
            src, _ = X.export(env, ['rust_elf_regs_bounded'], values,
                              ['#print axioms rust_elf_regs_bounded'])
            return src
        src = rustprove.in_big_stack(work)
        path = os.path.join(GEN, 'rust_elf_regs.lean')
        with open(path, 'w') as fh:
            fh.write(src)
        secs, ok, clean = lean_check(path)
        out.append(macro('regsLeanSeconds', '%.1f' % secs))
        out.append(macro('regsLeanVerdict', 'accepted' if ok else 'REJECTED'))
        out.append(macro('regsLeanNoAxioms', clean))

    # -- the safety lift over a table of shapes ----------------------------------
    from tests.test_rustproof import SAFETY, SAFE
    sp = rustprove.Prover(SAFETY)
    rows, agree = [], True
    for name, expected in SAFE.items():
        verdicts = sp.safety(name)
        ok = all(v for _, v in verdicts)
        agree = agree and ok == expected
        rows.append('\\texttt{%s} & %d & %s \\\\' % (
            tex(name), len(verdicts), 'all proved' if ok else 'open'))
    with open(os.path.join(GEN, 'safety_table.tex'), 'w') as fh:
        fh.write('\n'.join(rows) + '\n\\bottomrule\n')
    out.append(macro('safetyShapes', len(SAFE)))
    out.append(macro('safetyAgrees', 'agree' if agree else 'DISAGREE'))
    with open(os.path.join(GEN, 'early_sub_safe.py'), 'w') as fh:
        fh.write(lift(SAFETY, 'early_sub').safety())

    # -- alloc.rs -----------------------------------------------------------------
    alloc = source(os.path.join(CRUST, 'leanos', 'alloc.rs'))
    ap = rustprove.Prover(alloc)
    out.append(macro('allocRefused', len(ap.refused)))
    out.append(macro('allocFunctions', len(ap.lifted)))
    with open(os.path.join(GEN, 'bump_lifted.py'), 'w') as fh:
        fh.write(ap.lifted['bump'].source)
    t0 = time.time()
    total = proved_n = 0
    rows, opens = [], []
    for name in sorted(ap.lifted):
        fn = ap.lifted[name]
        if fn.ensures:
            v = ap.contract(name)
            rows.append('\\texttt{%s} & ensures \\texttt{%s} & %s \\\\' % (
                tex(name), tex(' and '.join(fn.ensures)),
                'proved' if v else 'open'))
        for label, ok in ap.safety(name):
            total += 1
            proved_n += ok
            rows.append('\\texttt{%s} & %s & %s \\\\' % (
                tex(name), tex(label), 'proved' if ok else 'open'))
            if not ok:
                opens.append(label)
    out.append(macro('allocSeconds', '%.1f' % (time.time() - t0)))
    with open(os.path.join(GEN, 'alloc_table.tex'), 'w') as fh:
        fh.write('\n'.join(rows) + '\n\\bottomrule\n')
    out.append(macro('allocObligations', total))
    out.append(macro('allocProved', proved_n))
    out.append(macro('allocOpen', total - proved_n))
    out.append(macro('allocOpenAllAdds',
                     'all' if all('`+`' in o for o in opens) else 'NOT ALL'))
    out.append(macro('bumpMonotone',
                     'proved' if ap.contract('bump') else 'open'))
    from tests.test_alloc_model import CORPUS
    out.append(macro('allocCorpusRows', len(CORPUS)))

    # -- compact numerals ---------------------------------------------------------
    def timed(length, bounds):
        t0 = time.time()
        try:
            r = C.check(length, bounds)
        except Exception as exc:
            r = str(exc)
        return time.time() - t0, r
    for tag, n, b in (('numSixtyFour', 64, {'len>=': 64}),
                      ('numMillion', 10 ** 6, {'len>=': 64}),
                      ('numUThirtyTwo', 2 ** 32 - 1, {'len>=': 64}),
                      ('numUSixtyFour', 2 ** 64 - 1, {'len<=': 2 ** 64 - 1})):
        secs, r = timed(n, b)
        out.append(macro(tag + 'Seconds', '%.4f' % secs))
        out.append(macro(tag + 'Verdict',
                         'proved' if str(r).startswith('proved') else 'other'))
    out.append(macro('numDivByFour',
                     'not proved' if 'not proved' in
                     str(timed(2 ** 32 - 1, {'div-by': 4})[1]) else 'PROVED'))
    out.append(macro('litIsOneNode',
                     'yes' if isinstance(L.numeral(2 ** 64 - 1), L.NatLit)
                     else 'NO'))
    out.append(macro('litDefEq', 'equal' if L.definitionally_equal(
        L.unary(5), L.numeral(5), L.GLOBAL_ENV) else 'NOT EQUAL'))
    out.append(macro('preludeDecls', len(H.prelude())))
    out.append(macro('acceleratedOps', len(H.ACCELERATED)))

    # -- kernel and prover selftests, as the run sees them --------------------------
    for tag, cmd in (('kernelChecks', ['python3', 'lean4.py', '--selftest']),
                     ('hoareChecks', ['python3', 'hoare.py'])):
        run = subprocess.run(cmd, cwd=HERE, capture_output=True, text=True,
                             timeout=900)
        last = run.stdout.strip().splitlines()[-1]
        out.append(macro(tag, last.split()[0]))
        out.append(macro(tag + 'Verdict',
                         'all passed' if 'all passed' in last else 'FAILED'))

    if LEAN:
        ver = subprocess.run([LEAN, '--version'], capture_output=True,
                             text=True).stdout.strip()
        out.append(macro('leanVersion', ver.split('(version ')[1].split(',')[0]))
    else:
        out.append(macro('leanVersion', 'not installed'))
    out.append(macro('crustDir', CRUST.replace('_', r'\_')))

    with open(os.path.join(GEN, 'rustproof_facts.tex'), 'w') as fh:
        fh.writelines(out)
    print(''.join(out))


if __name__ == '__main__':
    threading.stack_size(512 * 1024 * 1024)
    t = threading.Thread(target=lambda: main('--no-lean' not in sys.argv))
    t.start()
    t.join()
